[project]
name = "myfirstprojectintrae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "python-dotenv>=1.2.1",
]
